### ISSUE TITLE
No edit range operator in Blender 2.80.75

### ISSUE THREAD

**Issue by marcodsad** [wilecoyote2015/Blender_Addons#3]
Hi there,

[Blender 2.80.75 on Linux Mint 19]

just installed SunTools and trying to follow the usage instructions (at the github page) I realised there's no Edit Range operator in the Properties panel of my Sequencer. I can see Movie Manager and Trim Tools operators, but no Edit Range. So the addon is effectively unusable.

Am I missing something?

Also, as soon as I click on Set as Timeline, all Movie Manager options disappear, not sure if it's related.

Thank you!
best,

**Comment by wilecoyote2015** [comment]
Hi!
Actually, this is a documentation issue. Thanks for pointing me to this!

I've updated the doc and I hope that the usage is now described properly:
Actually, with the last update, the edit range operator had been moved to the file browser's panel. 

It is intended that, as soon as the current scene is set as timeline, the operators in the Sequencer's Movie manager panel disappear. This is because the operators are intended to insert the pretrimmed strips from another scene that is not the timeline scene into the timeline scene.

I hope that it works for you. If not, feel free to ask any questions!

**Comment by marcodsad** [comment]
Hi! thanks for the prompt reply, and glad to be of help :)

Now I found the Edit Range, great. Unfortunately, still SunTools is not working as I read it should.
But I'll investigate further and open a dedicate thread, since this thread has been solved.

thanks
